# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import screen_tools_pb2 as proto_dot_screen__tools__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/screen_tools_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScreenToolsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TakeScreenshot = channel.unary_unary(
                '/screen_tools.ScreenToolsService/TakeScreenshot',
                request_serializer=proto_dot_screen__tools__pb2.ScreenshotRequest.SerializeToString,
                response_deserializer=proto_dot_screen__tools__pb2.ScreenshotResponse.FromString,
                _registered_method=True)
        self.SaveScreenshot = channel.unary_unary(
                '/screen_tools.ScreenToolsService/SaveScreenshot',
                request_serializer=proto_dot_screen__tools__pb2.SaveScreenshotRequest.SerializeToString,
                response_deserializer=proto_dot_screen__tools__pb2.SaveResponse.FromString,
                _registered_method=True)
        self.ExecuteMouseAction = channel.unary_unary(
                '/screen_tools.ScreenToolsService/ExecuteMouseAction',
                request_serializer=proto_dot_screen__tools__pb2.MouseActionRequest.SerializeToString,
                response_deserializer=proto_dot_screen__tools__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.PerformOCR = channel.unary_unary(
                '/screen_tools.ScreenToolsService/PerformOCR',
                request_serializer=proto_dot_screen__tools__pb2.OCRRequest.SerializeToString,
                response_deserializer=proto_dot_screen__tools__pb2.OCRResponse.FromString,
                _registered_method=True)
        self.SaveCoordinates = channel.unary_unary(
                '/screen_tools.ScreenToolsService/SaveCoordinates',
                request_serializer=proto_dot_screen__tools__pb2.CoordinatesRequest.SerializeToString,
                response_deserializer=proto_dot_screen__tools__pb2.SaveResponse.FromString,
                _registered_method=True)
        self.GetCoordinates = channel.unary_unary(
                '/screen_tools.ScreenToolsService/GetCoordinates',
                request_serializer=proto_dot_screen__tools__pb2.CoordinatesRequest.SerializeToString,
                response_deserializer=proto_dot_screen__tools__pb2.CoordinatesResponse.FromString,
                _registered_method=True)
        self.SyncScreenData = channel.unary_unary(
                '/screen_tools.ScreenToolsService/SyncScreenData',
                request_serializer=proto_dot_screen__tools__pb2.ScreenDataRequest.SerializeToString,
                response_deserializer=proto_dot_screen__tools__pb2.SyncResponse.FromString,
                _registered_method=True)


class ScreenToolsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TakeScreenshot(self, request, context):
        """螢幕截圖相關
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveScreenshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteMouseAction(self, request, context):
        """滑鼠操作
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PerformOCR(self, request, context):
        """OCR 功能
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCoordinates(self, request, context):
        """座標管理
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCoordinates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncScreenData(self, request, context):
        """狀態同步
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScreenToolsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TakeScreenshot': grpc.unary_unary_rpc_method_handler(
                    servicer.TakeScreenshot,
                    request_deserializer=proto_dot_screen__tools__pb2.ScreenshotRequest.FromString,
                    response_serializer=proto_dot_screen__tools__pb2.ScreenshotResponse.SerializeToString,
            ),
            'SaveScreenshot': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveScreenshot,
                    request_deserializer=proto_dot_screen__tools__pb2.SaveScreenshotRequest.FromString,
                    response_serializer=proto_dot_screen__tools__pb2.SaveResponse.SerializeToString,
            ),
            'ExecuteMouseAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteMouseAction,
                    request_deserializer=proto_dot_screen__tools__pb2.MouseActionRequest.FromString,
                    response_serializer=proto_dot_screen__tools__pb2.ActionResponse.SerializeToString,
            ),
            'PerformOCR': grpc.unary_unary_rpc_method_handler(
                    servicer.PerformOCR,
                    request_deserializer=proto_dot_screen__tools__pb2.OCRRequest.FromString,
                    response_serializer=proto_dot_screen__tools__pb2.OCRResponse.SerializeToString,
            ),
            'SaveCoordinates': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCoordinates,
                    request_deserializer=proto_dot_screen__tools__pb2.CoordinatesRequest.FromString,
                    response_serializer=proto_dot_screen__tools__pb2.SaveResponse.SerializeToString,
            ),
            'GetCoordinates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoordinates,
                    request_deserializer=proto_dot_screen__tools__pb2.CoordinatesRequest.FromString,
                    response_serializer=proto_dot_screen__tools__pb2.CoordinatesResponse.SerializeToString,
            ),
            'SyncScreenData': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncScreenData,
                    request_deserializer=proto_dot_screen__tools__pb2.ScreenDataRequest.FromString,
                    response_serializer=proto_dot_screen__tools__pb2.SyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'screen_tools.ScreenToolsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('screen_tools.ScreenToolsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScreenToolsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TakeScreenshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/screen_tools.ScreenToolsService/TakeScreenshot',
            proto_dot_screen__tools__pb2.ScreenshotRequest.SerializeToString,
            proto_dot_screen__tools__pb2.ScreenshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveScreenshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/screen_tools.ScreenToolsService/SaveScreenshot',
            proto_dot_screen__tools__pb2.SaveScreenshotRequest.SerializeToString,
            proto_dot_screen__tools__pb2.SaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteMouseAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/screen_tools.ScreenToolsService/ExecuteMouseAction',
            proto_dot_screen__tools__pb2.MouseActionRequest.SerializeToString,
            proto_dot_screen__tools__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PerformOCR(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/screen_tools.ScreenToolsService/PerformOCR',
            proto_dot_screen__tools__pb2.OCRRequest.SerializeToString,
            proto_dot_screen__tools__pb2.OCRResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCoordinates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/screen_tools.ScreenToolsService/SaveCoordinates',
            proto_dot_screen__tools__pb2.CoordinatesRequest.SerializeToString,
            proto_dot_screen__tools__pb2.SaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCoordinates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/screen_tools.ScreenToolsService/GetCoordinates',
            proto_dot_screen__tools__pb2.CoordinatesRequest.SerializeToString,
            proto_dot_screen__tools__pb2.CoordinatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncScreenData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/screen_tools.ScreenToolsService/SyncScreenData',
            proto_dot_screen__tools__pb2.ScreenDataRequest.SerializeToString,
            proto_dot_screen__tools__pb2.SyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
